### ISSUE TITLE
PageNum should be Page in QueryString

### ISSUE THREAD

**Issue by Glusoft** [JustGiving/JustGiving.Api.Sdk#12]
Hi, 

I don't know if JustGiving have changed their APIs recently but I've found that the paging isn't working on the event requests when specifying a page number. 

The problem is the code provides the parameter in the query string 'PageNum' instead of 'Page'.  It seems to be throughout the code but I've only tested this on Event fundraising pages. 

```
        public string RetrieveDonationsForPageLocationFormat(string pageShortName, int? pageSize, int? pageNumber)
        {
            var locationFormat = ResourceBase + "/pages/" + pageShortName + "/donations";
            locationFormat += "?PageSize=" + pageSize.GetValueOrDefault(50);
            locationFormat += "&Page=" + pageNumber.GetValueOrDefault(1);
            return locationFormat;
        }

```

**Comment by markgibaud** [comment]
Hi @Glusoft 

Apologies, we should really remove the .NET SDK from this repo, as it is no longer supported. 

The good news is we have a brand new C# SDK here: https://github.com/JustGiving/JustGivingNETSDK

Please have a play with that one and see if you can get better results.

Can you let me know how you arrived at this repo? - We may need to update more links to the new repo.

**Comment by Glusoft** [comment]
Hi,

Thanks for coming back to me.

I looked at the other Repo but unfortunately it didn’t fit my requirements because it only provides Async methods.  I know why you’ve done this and it works great if supported but I use an external process to access the API and Async methods aren’t supported, not without extensive re-working of the base classes/interfaces anyway. In this old repo you have both async and synchronous methods which worked will.

I found this Repo via Nuget package manager in Visual Studio.

Cheers
Graham



[Glusoft Limited - Mailglu] <http://glusoft.uk>
Graham Till<mailto:graham@glusoft.uk> • Director<http://glusoft.uk>

Glusoft Limited<http://glusoft.uk> • glusoft.uk<http://glusoft.uk> • Derby<https://goo.gl/maps/Pp5usVa9nzk>

tel: +44 (0)1332 742581<tel:+441332742581> • mob: +44 (0)7793 457700<tel:+447793457700>


[Mailglu - The intelligent marketing solution] <http://mailglu.com>



On 3 Nov 2017, at 10:09, Mark Gibaud <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @Glusoft<https://github.com/glusoft>

Apologies, we should really remove the .NET SDK from this repo, as it is no longer supported.

The good news is we have a brand new C# SDK here: https://github.com/JustGiving/JustGivingNETSDK

Please have a play with that one and see if you can get better results.

Can you let me know how you arrived at this repo? - We may need to update more links to the new repo.

**Comment by pawelsawicz** [comment]
@Glusoft You can do invoke `Result()` on async method like `AsyncMethod.Result()` that way you will get synchronous call and you don't have to use async/await

**Comment by Glusoft** [comment]
Hi @pawelsawicz 

Thanks for this, but I believe you threadlock the main thread if you use Result().  Also, the fact my method doesn't return Task<t> is an issue. 

Not to worry, this works ok for what I need for the time being. 

Cheers
Graham
