### ISSUE TITLE
Campaigns?

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [JustGiving/JustGiving.Api.Sdk#7]
Is this the latest version of the SDK? Shouldn't it include the Campaign methods mentioned in the documentation?

https://api.justgiving.com/docs/resources/v1/Campaigns

Thanks.

**Comment by pawelsawicz** [comment]
Hey @JohnnyWalkerDesign ,

Depend which API, we are trying to not support .NET anymore, because we have plan to release brand new, much cleaner. If you talking about PHP, then yes we can add Campaigns.

Pawel

**Comment by JohnnyWalkerDesign** [comment]
I have a project that I need to finish by the end of this week. Do you think you will have Campaigns added to the SDK over the next day or so? Thanks.

**Comment by pawelsawicz** [comment]
@JohnnyWalkerDesign Are you talking about PHP SDK or .NET SDK ?

**Comment by JohnnyWalkerDesign** [comment]
Sorry, PHP.

**Comment by pawelsawicz** [comment]
@JohnnyWalkerDesign Yeah we will pick up tomorrow around :)

**Comment by JohnnyWalkerDesign** [comment]
Great. If not, I will make a start on it myself. Thanks.
